version: '3.1'

services:


        notebook:
                build: .
                image: kaggle
                restart: always
                ports:
                        - 8888:8888
                volumes:
                        - ./data:/tmp/data
                        - ./work:/home/jovyan/work
